### ISSUE TITLE
Apply ribbon to build type that not is in your list of build types

### ISSUE THREAD

**Issue by VasileUngureanu** [akaita/easylauncher-gradle-plugin#14]
Hi,

I have debug, qa and release build types.
For "debug" build type is work perfectly but for "qa" no ((

I have multi flavored app and each flavor is another application version.
I cannot use "qa" as flavor because every flavored application need to have debug, qa and release versions.

Thanks!

**Comment by akaita** [comment]
Hi,

Easylauncher adds a ribbon to all debuggable buildTypes by default. I guess your `qa` type is not debuggable?

If I understand correctly, you just want to do this:
```
easylauncher {
    buildTypes {
        qa {
            filters = blueRibbonFilter()
        }
    }
}
```

Does that work?

**Comment by VasileUngureanu** [comment]
Your are absolutely right!

I have something like this:

` qa {
      initWith release
}`

and release build type is not debuggable ))

It should work then!

Thanks!

**Comment by akaita** [comment]
Happy to help :)
