### ISSUE TITLE
Add possibility to modify text of ribbon

### ISSUE THREAD

**Issue by emartynov** [akaita/easylauncher-gradle-plugin#15]
We have `acceptance` as ribbon text and it is really small on the home launcher. It would be nice to change it to `ACC` maybe.

**Comment by emartynov** [comment]
Also because of different text length, easy launcher adapts font size and ribbon becomes smaller for longer texts.

**Comment by akaita** [comment]
I had this in my TODO list, but I somehow forgot to put it into the issues lists. Thanks for adding it 👍 

I think you second proposal is also sensible, I created https://github.com/akaita/easylauncher-gradle-plugin/issues/17 to reflect it

**Comment by akaita** [comment]
@emartynov I believe you can now change the text of the label with `customColorRibbonFilter("label", "#DCDCDC")`, so this issue can be closed. 
I will today work on #17 to make text sizes consistent
