### ISSUE TITLE
Duplicate Resources

### ISSUE THREAD

**Issue by adrianrdzv** [akaita/easylauncher-gradle-plugin#18]
Seems that the generated icons conflict with the original icons:
I get the following error:
```
[mipmap-mdpi-v4/ic_launcher] /Users/adrian/Repos/client/app/src/appMobileDebug/res/mipmap-mdpi/ic_launcher.png        [mipmap-mdpi-v4/ic_launcher] /Users/adrian/Repos/client/app/build/generated/ribbonizer/res/appMobileDebug/mipmap-mdpi/ic_launcher.png: Error: Duplicate resources
```

**Comment by akaita** [comment]
I can clearly read `ribbonizer` in the path.
Are you sure you are reporting in the correct repo?

**Comment by adrianrdzv** [comment]
Yes. Sorry I must have copied of when I tried with ribbonizer but it happens on both libraries. I'm not sure what is the cause of this issue.

**Comment by akaita** [comment]
Could you provide the error messages?

**Comment by akaita** [comment]
Closing due to lack of response.
Please reopen if you find you can provide the info required to confirm the issue.

**Comment by anvob** [comment]
I have the same problem with duplicate resources in one of buildType variants

Error message:
> mergeProdDebugResources FAILED
[mipmap-xhdpi-v4/ic_launcher_foreground] /home/user/app1/src/prodDebug/res/mipmap-xhdpi/ic_launcher_foreground.png	[mipmap-xhdpi-v4/ic_launcher_foreground] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xhdpi/ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-xhdpi-v4/ic_launcher] /home/user/app1/src/prodDebug/res/mipmap-xhdpi/ic_launcher.png	[mipmap-xhdpi-v4/ic_launcher] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xhdpi/ic_launcher.png: Error: Duplicate resources
[mipmap-xhdpi-v4/ic_launcher_round] /home/user/app1/src/prodDebug/res/mipmap-xhdpi/ic_launcher_round.png	[mipmap-xhdpi-v4/ic_launcher_round] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xhdpi/ic_launcher_round.png: Error: Duplicate resources
[mipmap-xxhdpi-v4/ic_launcher_foreground] /home/user/app1/src/prodDebug/res/mipmap-xxhdpi/ic_launcher_foreground.png	[mipmap-xxhdpi-v4/ic_launcher_foreground] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xxhdpi/ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-xxhdpi-v4/ic_launcher] /home/user/app1/src/prodDebug/res/mipmap-xxhdpi/ic_launcher.png	[mipmap-xxhdpi-v4/ic_launcher] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xxhdpi/ic_launcher.png: Error: Duplicate resources
[mipmap-xxhdpi-v4/ic_launcher_round] /home/user/app1/src/prodDebug/res/mipmap-xxhdpi/ic_launcher_round.png	[mipmap-xxhdpi-v4/ic_launcher_round] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xxhdpi/ic_launcher_round.png: Error: Duplicate resources
[mipmap-mdpi-v4/ic_launcher_foreground] /home/user/app1/src/prodDebug/res/mipmap-mdpi/ic_launcher_foreground.png	[mipmap-mdpi-v4/ic_launcher_foreground] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-mdpi/ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-mdpi-v4/ic_launcher] /home/user/app1/src/prodDebug/res/mipmap-mdpi/ic_launcher.png	[mipmap-mdpi-v4/ic_launcher] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-mdpi/ic_launcher.png: Error: Duplicate resources
[mipmap-mdpi-v4/ic_launcher_round] /home/user/app1/src/prodDebug/res/mipmap-mdpi/ic_launcher_round.png	[mipmap-mdpi-v4/ic_launcher_round] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-mdpi/ic_launcher_round.png: Error: Duplicate resources
[mipmap-hdpi-v4/ic_launcher_foreground] /home/user/app1/src/prodDebug/res/mipmap-hdpi/ic_launcher_foreground.png	[mipmap-hdpi-v4/ic_launcher_foreground] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-hdpi/ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-hdpi-v4/ic_launcher] /home/user/app1/src/prodDebug/res/mipmap-hdpi/ic_launcher.png	[mipmap-hdpi-v4/ic_launcher] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-hdpi/ic_launcher.png: Error: Duplicate resources
[mipmap-hdpi-v4/ic_launcher_round] /home/user/app1/src/prodDebug/res/mipmap-hdpi/ic_launcher_round.png	[mipmap-hdpi-v4/ic_launcher_round] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-hdpi/ic_launcher_round.png: Error: Duplicate resources
[mipmap-xxxhdpi-v4/ic_launcher_foreground] /home/user/app1/src/prodDebug/res/mipmap-xxxhdpi/ic_launcher_foreground.png	[mipmap-xxxhdpi-v4/ic_launcher_foreground] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xxxhdpi/ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-xxxhdpi-v4/ic_launcher] /home/user/app1/src/prodDebug/res/mipmap-xxxhdpi/ic_launcher.png	[mipmap-xxxhdpi-v4/ic_launcher] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xxxhdpi/ic_launcher.png: Error: Duplicate resources
[mipmap-xxxhdpi-v4/ic_launcher_round] /home/user/app1/src/prodDebug/res/mipmap-xxxhdpi/ic_launcher_round.png	[mipmap-xxxhdpi-v4/ic_launcher_round] /home/user/app1/build/generated/easylauncher/res/prodDebug/mipmap-xxxhdpi/ic_launcher_round.png: Error: Duplicate resources

**Comment by repitch** [comment]
Same problem. @akaita can we reopen issue?
