### ISSUE TITLE
Add option to customize the color of the text of ribbons

### ISSUE THREAD

**Issue by akaita** [akaita/easylauncher-gradle-plugin#2]

**Comment by arminelec** [comment]
I think you have already implemented this ticket and can be closed. Using 
```java
customColorRibbonFilter("label", "#DCDCDC", "#000000")
```
the label can have a custom color.
Or is this ticket about something else?

**Comment by akaita** [comment]
The code you mention allows you to change the background of the ribbon. 
As of now, the text is always white. Imagine you make the ribbon yellow... whit etext will be quite difficult to read.
I'd like to be able to change the text from white to other colors.

Thansk for checking, though!

**Comment by akaita** [comment]
Ha! Actually you are right, and th eplugin already does this! 
Silly me... thanks!
