### ISSUE TITLE
Ribbon text based on build variant

### ISSUE THREAD

**Issue by gustavkarlsson** [akaita/easylauncher-gradle-plugin#26]
Instead of basing the ribbon text on type OR flavor, why not add an option to use the full build variant name, ie. "stagingDebug", "betaRelease", etc?

I realize it might be pretty long, but I could live with that. Alternatively let the user provide a function to set a complete custom text...

**Comment by akaita** [comment]
Hi @gustavkarlsson ,  Thanks for the proposal, but I think this was part of the initial public release 🤔 .

```
    variants {
        productionDebug {
            // OVERRIDE all previous filters defined for `productionDebug` variant
            filters = customColorRibbonFilter("myCustomLabel", "#DCDCDC")
        }
    }
```

Doesn't this one work for you?

(feel free to reopen the issue if not)
