### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by ewoks** [akaita/easylauncher-gradle-plugin#30]
Can you please write something as release notes when new version comes out? 
I am updating from 1.2.0 to 1.3.1 and have no clue what are the changes. Thanks a lot for the effort

**Comment by akaita** [comment]
I see your point. You can already see that information in https://github.com/akaita/easylauncher-gradle-plugin/blob/master/CHANGELOG.md. 
I can see how some people won't even check for a changelog file (although you should). There's not that many releases for this project, so I could copy the info from the changelog.
