### ISSUE TITLE
Could not find method grayscaleFilter()

### ISSUE THREAD

**Issue by vipulasri** [akaita/easylauncher-gradle-plugin#31]
I am unable to sync the gradle , keep getting this error "Could not find method grayscaleFilter() for arguments [] on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, ....".

My configuration:

```
easylauncher {
        iconNames "@mipmap/ic_launcher_foreground" // Traditional launcher icon
        foregroundIconNames "@mipmap/ic_launcher_foreground" // Foreground of adaptive launcher icon
        defaultFlavorNaming = true // Use flavor name for default ribbon, instead of the type name

        buildTypes {
            debug {
                filters = grayscaleFilter()
            }
            staging {
                filters = [
                        customColorRibbonFilter("Staging", "#E65100")
                ]
            }
        }
    }
```

**Comment by akaita** [comment]
That same config worked fine for me. 
Can you try removing that one line (`filters = grayscaleFilter()`) to see what happens?

**Comment by vipulasri** [comment]
Tried in a new application. Worked Fine!

**Comment by akaita** [comment]
👍
