### ISSUE TITLE
Custom gravity not working with non-default icon

### ISSUE THREAD

**Issue by chinbri** [akaita/easylauncher-gradle-plugin#32]
Hi,

I have a problem in my app with custom gravity labels. All was working fine with the default-ugly android launcher icon, but when I change it to a new one (whatever), label position change:

Before:
![image](https://user-images.githubusercontent.com/45945979/53154711-aed71b00-35bb-11e9-9919-ccbad03c5bb2.png)

After:
![image](https://user-images.githubusercontent.com/45945979/53154301-c1048980-35ba-11e9-8415-692a0c67fd8a.png)

Here is my configuration:

    easylauncher {

    def internalDevelopRibbonColor = "#ffffff"

    iconNames "@mipmap/ic_launcher_foreground" // Traditional launcher icon
    foregroundIconNames "@mipmap/ic_launcher_foreground" // Foreground of adaptive launcher icon

    defaultFlavorNaming = true // Use flavor name for default ribbon, instead of the type name

    productFlavors {
        dev {
            filters = customColorRibbonFilter("DEV", internalDevelopRibbonColor, "#000000", "bottom", 0.20)
        }
		
		...
	}

Thanks!

**Comment by chinbri** [comment]
I think it was a problem with the ic_launcher_foreground image, because Android Studio image create it as a vector drawable

**Comment by akaita** [comment]
Oh, thanks for the update. 
I really want to add support for vector drawables 🤔
