### ISSUE TITLE
Ribbon is not added to API 26 adaptive-icon

### ISSUE THREAD

**Issue by eduardb** [akaita/easylauncher-gradle-plugin#8]
Hi! I tried out the plugin and it works great on devices with Nougat or lower, but it doesn't work with adaptive icons on Oreo. I only have debug and release build types, and I added this block in `app/build.gradle` right below the `android` block:
```groovy
easylauncher {
    iconNames "@mipmap/ic_launcher_foreground" 
    foregroundIconNames "@mipmap/ic_launcher_foreground" 
}
```
Is the plugin meant to support adaptive icons? Cheers!

**Comment by akaita** [comment]
Yes, it is meant to work with adaptive icons :)

The example configuration assumes you have a defined your adaptive icon in a way similar to this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
</adaptive-icon>
```

Could you share the definition of your adaptive icon?

**Comment by eduardb** [comment]
Sure, it's very similar with yours, only that the background is another drawable, not a color:
```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
```
Could that be the problem?

**Comment by akaita** [comment]
Yeah, you are just not pointing `Easylauncher` to the correct resource.

Please replace `foregroundIconNames "@mipmap/ic_launcher_foreground" ` with:
```
foregroundIconNames "@drawable/ic_launcher_foreground" 
```

**Comment by eduardb** [comment]
Ha, rookie mistake, but probably I wouldn't have spotted the difference for a long time, thanks for pointing out to me. However, even with the correct resource, it still doesn't seem to work... I forgot to mention though, `@drawable/ic_launcher_foreground` is a vector drawable. Maybe those aren't supported?

**Comment by akaita** [comment]
> Ha, rookie mistake

xD

> `@drawable/ic_launcher_foreground` is a vector drawable

True, I didn't add support for those... 
I created #9 so it doesn't get forgotten.

**Comment by eduardb** [comment]
Cool, thanks for your time! I hope to see vector drawable support soon :D
